services:
  db:
    image: postgres:16
    container_name: payment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: payment_service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: payment-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  pgdata: {}
